### ISSUE TITLE
url without page title

### ISSUE THREAD

**Issue by stefanobonetta** [pagemachine/typo3-flat-urls#78]
hi,
Is possible to remove the page title from the URL, in order to have:
https://mysite.it/23/
instead
https://mysite.it/23/page_title
Thanks

**Comment by mbrodala** [comment]
This surely could be an option if implemented wisely. I'd accept a PR for this.

**Comment by mbrodala** [comment]
Closing due to lack of further action, feel free to comment or suggest a change if you would like to see this done.
